name: CD Pipeline
on:
  workflow_dispatch:
  pull_request:
permissions:
  contents: read
  id-token: write
env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: "AWS_ACCOUNT_ID_REDACTED"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/gh_actions

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
