name: CI [Test] (Callable ONLY)

on:

  workflow_call:
    inputs:
      uv-version:
        required: true
        type: string

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: "AWS_ACCOUNT_ID_REDACTED"
  APP: "voting-vote"

permissions:
  id-token: write
  contents: read

jobs:
  ci-tests:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v7
        # with:
        #   fetch-depth: 0

      - uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/gh_actions

      - name: Login to ECR
        run: aws ecr get-login-password | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          # Install a specific version of uv.
          version: ${{ inputs.uv-version }}
          enable-cache: true

      - name: Install dependencies with uv
        run: uv sync --locked --all-groups ##Since UV is used as a virtual env for this

      - name: Run pytest
        env:
          REDIS_MASTER_ANNOUNCE_IP: ${{ vars.REDIS_MASTER_ANNOUNCE_IP }}
          REDIS_ANNOUNCE_IP: ${{ vars.REDIS_ANNOUNCE_IP }}
          REDIS_MASTER_HOST: ${{ vars.REDIS_MASTER_HOST }}
          REDIS_SENTINEL_HOST: ${{ vars.REDIS_SENTINEL_HOST }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_SENTINEL_PORT: ${{ vars.REDIS_SENTINEL_PORT }}
          REDIS_MASTER_NAME: ${{ vars.REDIS_MASTER_NAME }}
          REDIS_USER_NAME: ${{ vars.REDIS_USER_NAME }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          DB_HOST: ${{ vars.DB_HOST }}
          DB_PORT: ${{ vars.DB_PORT }}
          DB_USERNAME: ${{ vars.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB: ${{ vars.DB }}
          DB_SSL_MODE: ${{ vars.DB_SSL_MODE }}
        run: |
          uv run pytest

      # - name: Run Trivy vulnerability scanner
      #   uses: aquasecurity/trivy-action@v0.36.0
      #   with:
      #     image-ref: '${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.APP }}:${{ github.event.pull_request.head.sha }}'
      #     format: 'table'
      #     exit-code: '1'
      #     ignore-unfixed: true
