name: CI [Test] (Callable ONLY)

on:

  workflow_call:
    inputs:
      uv-version:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  ci-tests-and-build:
    environment:
      name: prod
      deployment: false
    runs-on: ubuntu-latest
    steps:

      - name: Create interpolated env var
        run: echo "DOCKER_IMAGE_URI=${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.APP }}:${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

      - name: Checkout local Git Repo
        uses: actions/checkout@v7.0.1

      - uses: aws-actions/configure-aws-credentials@v6.2.4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.OIDC_ROLE_NAME }}

      - name: Login to ECR
        run: aws ecr get-login-password | docker login --username AWS --password-stdin ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com

      - name: Build and tag docker image
        run: |
          docker build --pull --no-cache . -t ${{ env.DOCKER_IMAGE_URI }}

      - name: Grab latest Image Tag from dependent containers
        run: |
          repo_list=( ${{ vars.RESULTS_ECR_REPO_NAME }} ${{ vars.WORKER_ECR_REPO_NAME }} )

          for repo in ${repo_list[*]}; do
              IMAGE_TAG=$(aws ecr describe-images --repository-name $repo --query 'imageDetails | sort_by(@, &imagePushedAt)[-1].imageTags[0]' --output text)
              repo_upper=${repo^^}
              repo_upper_normalized=${repo_upper//-/_}
              echo "${repo_upper_normalized}_LATEST_IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          done

      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          # Install a specific version of uv.
          version: ${{ inputs.uv-version }}
          enable-cache: true

      - name: Install dependencies with uv
        run: uv sync --frozen --all-groups

##DEBUG ONLY
      # - name: Run Docker compose as a test
      #   run: |
      #     docker compose up
      #   env:
      #     REDIS_MASTER_ANNOUNCE_IP: ${{ vars.REDIS_MASTER_ANNOUNCE_IP }}
      #     REDIS_ANNOUNCE_IP: ${{ vars.REDIS_ANNOUNCE_IP }}
      #     REDIS_MASTER_HOST: ${{ vars.REDIS_MASTER_HOST }}
      #     REDIS_SENTINEL_HOST: ${{ vars.REDIS_SENTINEL_HOST }}
      #     REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      #     REDIS_SENTINEL_PORT: ${{ vars.REDIS_SENTINEL_PORT }}
      #     REDIS_MASTER_NAME: ${{ vars.REDIS_MASTER_NAME }}
      #     REDIS_USER_NAME: ${{ vars.REDIS_USER_NAME }}
      #     POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      #     POSTGRES_USER: ${{ vars.POSTGRES_USER }}
      #     DB_HOST: ${{ vars.DB_HOST }}
      #     DB_PORT: ${{ vars.DB_PORT }}
      #     DB_USERNAME: ${{ vars.DB_USERNAME }}
      #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      #     DB: ${{ vars.DB }}
      #     DB_SSL_MODE: ${{ vars.DB_SSL_MODE }}
      #     DOCKER_IMAGE_URI: ${{ env.DOCKER_IMAGE_URI }}
      #     VOTING_RESULTS_LATEST_IMAGE_TAG: ${{ env.VOTING_RESULTS_LATEST_IMAGE_TAG }}
      #     VOTING_WORKER_LATEST_IMAGE_TAG: ${{ env.VOTING_WORKER_LATEST_IMAGE_TAG }}
      #     DOCKER_IMAGE_TAG: ${{ github.event.pull_request.head.sha }}
      #     AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}

      #   continue-on-error: true

      # - name: Get docker compose logs
      #   run: |
      #     docker compose logs
      #   env:
      #     REDIS_MASTER_ANNOUNCE_IP: ${{ vars.REDIS_MASTER_ANNOUNCE_IP }}
      #     REDIS_ANNOUNCE_IP: ${{ vars.REDIS_ANNOUNCE_IP }}
      #     REDIS_MASTER_HOST: ${{ vars.REDIS_MASTER_HOST }}
      #     REDIS_SENTINEL_HOST: ${{ vars.REDIS_SENTINEL_HOST }}
      #     REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      #     REDIS_SENTINEL_PORT: ${{ vars.REDIS_SENTINEL_PORT }}
      #     REDIS_MASTER_NAME: ${{ vars.REDIS_MASTER_NAME }}
      #     REDIS_USER_NAME: ${{ vars.REDIS_USER_NAME }}
      #     POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      #     POSTGRES_USER: ${{ vars.POSTGRES_USER }}
      #     DB_HOST: ${{ vars.DB_HOST }}
      #     DB_PORT: ${{ vars.DB_PORT }}
      #     DB_USERNAME: ${{ vars.DB_USERNAME }}
      #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      #     DB: ${{ vars.DB }}
      #     DB_SSL_MODE: ${{ vars.DB_SSL_MODE }}
      #     DOCKER_IMAGE_URI: ${{ env.DOCKER_IMAGE_URI }}
      #     VOTING_RESULTS_LATEST_IMAGE_TAG: ${{ env.VOTING_RESULTS_LATEST_IMAGE_TAG }}
      #     VOTING_WORKER_LATEST_IMAGE_TAG: ${{ env.VOTING_WORKER_LATEST_IMAGE_TAG }}
      #     DOCKER_IMAGE_TAG: ${{ github.event.pull_request.head.sha }}
      #     AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
      # - name: show compose contents
      #   run: cat compose.yml
##DEBUG ONLY

      - name: Run pytest
        env:
          REDIS_MASTER_ANNOUNCE_IP: ${{ vars.REDIS_MASTER_ANNOUNCE_IP }}
          REDIS_ANNOUNCE_IP: ${{ vars.REDIS_ANNOUNCE_IP }}
          REDIS_MASTER_HOST: ${{ vars.REDIS_MASTER_HOST }}
          REDIS_SENTINEL_HOST: ${{ vars.REDIS_SENTINEL_HOST }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_SENTINEL_PORT: ${{ vars.REDIS_SENTINEL_PORT }}
          REDIS_MASTER_NAME: ${{ vars.REDIS_MASTER_NAME }}
          REDIS_USER_NAME: ${{ vars.REDIS_USER_NAME }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          DB_HOST: ${{ vars.DB_HOST }}
          DB_PORT: ${{ vars.DB_PORT }}
          DB_USERNAME: ${{ vars.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB: ${{ vars.DB }}
          DB_SSL_MODE: ${{ vars.DB_SSL_MODE }}
          DOCKER_IMAGE_URI: ${{ env.DOCKER_IMAGE_URI }}
          VOTING_RESULTS_LATEST_IMAGE_TAG: ${{ env.VOTING_RESULTS_LATEST_IMAGE_TAG }}
          VOTING_WORKER_LATEST_IMAGE_TAG: ${{ env.VOTING_WORKER_LATEST_IMAGE_TAG }}
          DOCKER_IMAGE_TAG: ${{ github.event.pull_request.head.sha }}
          AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
        run: |
          uv run pytest

      - name: Push docker image
        run: |
          docker push ${{ env.DOCKER_IMAGE_URI }}

      # - name: Run Trivy vulnerability scanner
      #   uses: aquasecurity/trivy-action@v0.36.0
      #   with:
      #     image-ref: '${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.APP }}:${{ github.event.pull_request.head.sha }}'
      #     format: 'table'
      #     exit-code: '1'
      #     ignore-unfixed: true
